/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (2Xtreme)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80012644u
#define func_80012644 BootEntry  /* alias */
